import { ImageForm } from "@/core/upload/forms/imageForm";
import { Metadata } from "next";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";
import { authOptions } from "../api/auth/[...nextauth]/route";

export const metadata: Metadata = {
  title: "Upload - Geek.pics",
  description: "Generated by create next app",
};

const getCategorys = async () => {
  const response = await fetch(`${process.env.API_URL}/api/category`, {
    next: {
      revalidate: 3600,
    },
  });
  console.log("CONTENT TYPE ", response.headers.get("content-type"));
  if (response.headers.get("content-type") !== "application/json") {
    return [];
  }
  const data = await response.json();
  return data;
};

export interface Category {
  id: string;
  name: string;
  createdAt: Date;
  updatedAt: Date;
  enabled: boolean;
}

export default async function UploadPage() {
  const session = await getServerSession(authOptions);

  if (session?.user?.role?.id !== "cdf104fd-1a2b-4178-bce5-df92ed430170")
    redirect("/");

  if (!session) {
    redirect("/api/auth/signin");
  }

  const categorys = await getCategorys();

  return (
    <section className="p-5 flex flex-col gap-2 justify-center items-center">
      <h2 className="inline-flex animate-text-gradient bg-gradient-to-r from-[#b2a8fd] via-[#8678f9] to-[#c7d2fe] bg-[200%_auto] bg-clip-text text-4xl text-transparent">
        Upload
      </h2>
      <ImageForm categorys={categorys} />
    </section>
  );
}
